<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="project" nsURI="http://whz.de/modeling/project" nsPrefix="project">
  <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="int"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Long" instanceClassName="long"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Float" instanceClassName="float"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Double" instanceClassName="double"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Byte" instanceClassName="byte"/>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Date" instanceClassName="java.util.Calendar"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="java.lang.Boolean"/>
  <eClassifiers xsi:type="ecore:EDataType" name="UUID" instanceClassName="java.util.UUID"/>
  <eClassifiers xsi:type="ecore:EClass" name="Organization" eSuperTypes="#//IIdentifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" ordered="false"
        upperBound="-1" eType="#//Project" containment="true" eOpposite="#//Project/organization">
      <eAnnotations source="http://www.vsd-project.org/vsee/annotation/description">
        <details key="text" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" ordered="false"
        upperBound="-1" eType="#//Person" containment="true" eOpposite="#//Person/organization">
      <eAnnotations source="http://www.vsd-project.org/vsee/annotation/description">
        <details key="text" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="#//IIdentifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="organization" ordered="false"
        lowerBound="1" eType="#//Organization" eOpposite="#//Organization/projects">
      <eAnnotations source="http://www.vsd-project.org/vsee/annotation/description">
        <details key="text" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participant" ordered="false"
        upperBound="-1" eType="#//Participant" containment="true" eOpposite="#//Participant/project">
      <eAnnotations source="http://www.vsd-project.org/vsee/annotation/description">
        <details key="text" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" eSuperTypes="#//IIdentifiable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="validWorkload"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weeklyWorkload" ordered="false"
        lowerBound="1" eType="#//HoursPerWeek"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" ordered="false"
        lowerBound="1" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalWeeklyWorkload" ordered="false"
        lowerBound="1" eType="#//HoursPerWeek" changeable="false" transient="true"
        defaultValueLiteral="0" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organization" ordered="false"
        lowerBound="1" eType="#//Organization" eOpposite="#//Organization/employees">
      <eAnnotations source="http://www.vsd-project.org/vsee/annotation/description">
        <details key="text" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participates" ordered="false"
        upperBound="-1" eType="#//Participant" eOpposite="#//Participant/person">
      <eAnnotations source="http://www.vsd-project.org/vsee/annotation/description">
        <details key="text" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IIdentifiable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" ordered="false" lowerBound="1"
        eType="#//UUID" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="HoursPerWeek" instanceClassName="java.lang.Integer"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ParticipantRole">
    <eLiterals name="Developer" literal="Developer"/>
    <eLiterals name="Tester" value="1" literal="Tester"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Participant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" ordered="false" lowerBound="1"
        eType="#//ParticipantRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weeklyWorkload" ordered="false"
        lowerBound="1" eType="#//HoursPerWeek"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" ordered="false"
        lowerBound="1" eType="#//Project" eOpposite="#//Project/participant">
      <eAnnotations source="http://www.vsd-project.org/vsee/annotation/description">
        <details key="text" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" ordered="false"
        lowerBound="1" eType="#//Person" eOpposite="#//Person/participates">
      <eAnnotations source="http://www.vsd-project.org/vsee/annotation/description">
        <details key="text" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
